os: Visual Studio 2017
version: 2.1.{build}

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  NUGET_XMLDOC_MODE: skip

branches:
  only:
    - master

cache:
  - src\LondonTravel.Site\node_modules
  - '%APPDATA%\npm\node_modules'
  - '%APPDATA%\npm-cache'

install:
  - ps: npm install -g npm@6.1.0 --loglevel=error
  - ps: npm install -g gulp@3.9.1 --loglevel=error

build_script:
  #- curl --header "Content-Type: application/json" --request POST --data '[{"testName":"Site Map Locations Are Valid","testFramework":"xUnit","fileName":"LondonTravel.Site.Tests.dll (.NETCoreApp,Version=v2.1)","outcome":"Passed","durationMilliseconds":135,"StdOut":""}]' %APPVEYOR_API_URL%/api/tests/batch
  - curl
  - echo %APPVEYOR_API_URL%
  - ps: .\Build.ps1
  
  #- ps: $dotnetPath = (Get-Command "dotnet.exe").Source
  #- ps: C:\Users\appveyor\.nuget\packages\opencover\4.6.519\tools\OpenCover.Console.exe -target:$dotnetPath -targetargs:"test c:/projects/alexa-london-travel-site/tests/LondonTravel.Site.Tests/LondonTravel.Site.Tests.csproj --output C:/Projects/alexa-london-travel-site\artifacts" -output:"C:/Projects/alexa-london-travel-site\artifacts/code-coverage.xml" -excludebyattribute:*.ExcludeFromCodeCoverage -hideskipped:All -mergebyhash -oldstyle -register:user -skipautoprops -filter:"+[LondonTravel.Site]* +[LondonTravel.Site.Views]* -[LondonTravel.Site.Tests]*"
  #- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

after_build:
    
    - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
    - pip install codecov
    - codecov -f "artifacts\code-coverage.xml"

artifacts:
  - path: artifacts\publish
  - path: artifacts\code-coverage.xml
  - path: artifacts\*.png

nuget:
  disable_publish_on_pr: true

skip_tags: false
#on_finish:
 # - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
test: off
